name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            preset: linux-release
            container_image: ebnfparser:latest 
          - os: windows-latest
            preset: windows-debug
            container_image: ""

    runs-on: ${{ matrix.os }}
    
    container: ${{ matrix.container_image != '' && matrix.container_image || null }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Container
        if: matrix.os == 'ubuntu-latest'
        run: docker build -t ebnfparser:latest .

      - name: Configure CMake
        run: cmake --preset ${{ matrix.preset }}

      - name: Build Project
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Test
        run: ctest --test-dir build/${{ matrix.preset == 'linux-release' && 'release' || 'debug' }}
