name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      run_exhaustive:
        description: 'Run exhaustive tests and secondary platforms?'
        type: boolean
        required: false
        default: false

  schedule:
    - cron: '0 2 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-26.04
            preset: linux-release
            is_cygwin: false
            exhaustive: false
          - os: windows-latest
            preset: windows-debug
            is_cygwin: false
            exhaustive: false
          - os: windows-latest
            preset: cygwin-release
            is_cygwin: true
            exhaustive: true
          - os: macos-latest
            preset: mac-release
            is_cygwin: false
            exhaustive: false

    runs-on: ${{ matrix.os }}

    env:
      SHELLOPTS: igncr

    steps:
# condition to skip steps for os in exhaustive list unless scheduled or manual run
      - uses: actions/checkout@v4
        if: |
          matrix.exhaustive == false ||
          github.event_name == 'schedule' ||
          (github.event_name == 'workflow_dispatch' && inputs.run_exhaustive == true)


# Linux setup

      - name: Linux setup
        if: matrix.os == 'ubuntu-26.04'
        run: |
          sudo apt update
          sudo apt install -y gcc-16 g++-16 cmake ninja-build bison flex libfl-dev
          echo "CC=gcc-16" >> $GITHUB_ENV
          echo "CXX=g++-16" >> $GITHUB_ENV

      - name: Linux versions
        if: matrix.os == 'ubuntu-26.04'
        run: |
          echo "--- Linux versions ---"
          echo "uname -a"
          uname -a
          echo "lsb_release -a"
          lsb_release -a
          echo "g++ --version"
          g++-16 --version
          echo "cmake --version"
          cmake --version
          echo "bison --version"
          bison --version
          echo "flex --version"
          flex --version
          echo "ls -l FlexLexer.h"
          ls -l /usr/include/FlexLexer.h

# Windows setup

      - name: Windows versions
        if: matrix.os == 'windows-latest' && matrix.is_cygwin == false
        run: |
          echo "--- Windows versions ---"
          echo "cmake --version"
          cmake --version

# Mac setup

      - name: Mac setup
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install gcc cmake ninja bison flex
          echo "CC=gcc-16" >> $GITHUB_ENV
          echo "CXX=g++-16" >> $GITHUB_ENV
          echo "BISON_ROOT=$(brew --prefix bison)" >> $GITHUB_ENV
          echo "FLEX_ROOT=$(brew --prefix flex)" >> $GITHUB_ENV

      - name: Mac versions
        if: matrix.os == 'macos-latest'
        run: |
          echo "--- Mac versions ---"
          echo "uname -a"
          uname -a
          echo "sw_vers"
          sw_vers
          echo "g++ --version"
          g++-16 --version
          echo "cmake --version"
          cmake --version
          echo "bison --version"
          $(brew --prefix bison)/bin/bison --version
          echo "flex --version"
          $(brew --prefix flex)/bin/flex --version
          echo "ls -l FlexLexer.h"
          ls -l $(brew --prefix flex)/include/FlexLexer.h

# Non-Cygwin build and test

      - name: CMake Configure
        if: matrix.is_cygwin == false
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        if: matrix.is_cygwin == false
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Run Tests
        if: matrix.is_cygwin == false
        run: ctest --preset ${{ matrix.preset }} --output-on-failure

# Cygwin setup

      - name: Cygwin setup
        if: |
          matrix.is_cygwin == true &&
          (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.run_exhaustive == true))
        uses: cygwin/cygwin-install-action@v6
        with:
          platform: x64
          allow-test-packages: 'true'
          packages: cmake ninja gcc-core=16.1.0+20260613-0.1 gcc-g++=16.1.0+20260613-0.1 bison flex

      - name: Cygwin versions
        if: |
          matrix.is_cygwin == true &&
          (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.run_exhaustive == true))
        shell: bash
        run: |
          echo "--- Cygwin versions ---"
          echo "uname -a"
          uname -a
          echo "g++ --version"
          g++ --version
          echo "cmake --version"
          cmake --version
          echo "bison --version"
          bison --version
          echo "flex --version"
          flex --version
          echo "ls -l FlexLexer.h"
          ls -l /usr/include/FlexLexer.h

# Cygwin build and test

      - name: Cygwin CMake Configure
        if: |
          matrix.is_cygwin == true &&
          (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.run_exhaustive == true))
        shell: bash
        run: |
          cmake --preset ${{ matrix.preset }}

      - name: Cygwin Build
        if: |
          matrix.is_cygwin == true &&
          (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.run_exhaustive == true))
        shell: bash
        run: |
          cmake --build --preset ${{ matrix.preset }}

      - name: Cygwin Run Tests
        if: |
          matrix.is_cygwin == true &&
          (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.run_exhaustive == true))
        shell: bash
        run: |
          ctest --preset ${{ matrix.preset }} --output-on-failure
