name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
      
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-26.04
            preset: linux-release
            is_cygwin: false
          - os: windows-latest
            preset: windows-debug
            is_cygwin: false
          - os: windows-latest
            preset: cygwin-debug
            is_cygwin: true

    runs-on: ${{ matrix.os }}
    
    env:
      SHELLOPTS: igncr

    steps:
      - uses: actions/checkout@v4

      - name: Linux setup
        if: matrix.os == 'ubuntu-26.04'
        run: |
          sudo apt update
          sudo apt install -y gcc-16 g++-16 cmake ninja-build bison flex libfl-dev
          echo "CC=gcc-16" >> $GITHUB_ENV
          echo "CXX=g++-16" >> $GITHUB_ENV

      - name: Linux versions
        if: matrix.os == 'ubuntu-26.04'
        run: |
          echo "--- Linux versions ---"
          echo "uname -a"
          uname -a
          echo "lsb_release -a"
          lsb_release -a
          echo "g++ --version"
          g++-16 --version
          echo "cmake --version"
          cmake --version
          echo "bison --version"
          bison --version
          echo "flex --version"
          flex --version
          echo "ls -l FlexLexer.h"
          ls -l /usr/include/FlexLexer.h

      - name: Windows versions
        if: matrix.os == 'windows-latest'
        run: |
          echo "--- Windows versions ---"
          echo "cmake --version"
          cmake --version

      - name: CMake Configure
        if: matrix.is_cygwin == false
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        if: matrix.is_cygwin == false
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Run Tests
        if: matrix.is_cygwin == false
        run: ctest --preset ${{ matrix.preset }} --output-on-failure

      - name: Cygwin setup
        if: matrix.is_cygwin == true
        uses: cygwin/cygwin-install-action@v4
        with:
          platform: x64
          extra-options: --enable-test-packages
          packages: cmake ninja gcc-g++=16.1.0+20260613-0.1 bison flex

      - name: Cygwin versions
        if: matrix.is_cygwin == true
        shell: bash
        run: |
          echo "--- Cygwin versions ---"
          echo "uname -a"
          uname -a
          echo "g++ --version"
          g++ --version
          echo "cmake --version"
          cmake --version
          echo "bison --version"
          bison --version
          echo "flex --version"
          flex --version
          echo "ls -l FlexLexer.h"
          ls -l /usr/include/FlexLexer.h

      - name: Cygwin CMake Configure
        if: matrix.is_cygwin == true
        shell: bash
        run: |
          cmake --preset ${{ matrix.preset }}

      - name: Cygwin Build
        if: matrix.is_cygwin == true
        shell: bash
        run: |
          cmake --build --preset ${{ matrix.preset }}

      - name: Cygwin Run Tests
        if: matrix.is_cygwin == true
        shell: bash
        run: |
          ctest --preset ${{ matrix.preset }} --output-on-failure
